version: '3.7'

services:
  api:
    build: .
    container_name: weather_api
    ports:
      - "8000:8000"
    networks:
      - monitoring
    volumes:
      - .:/app
      - ./data:/data
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
       - "9090:9090"
    networks:
      - monitoring

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - '^/(sys|proc|dev|host|etc)($|/)'
    networks:
      - monitoring

  swaggerui:
    image: swaggerapi/swagger-ui
    ports:
      - "80:8080"
    environment:
      - BASE_URL=/swagger
      - SWAGGER_JSON=weather_api:8000/openapi.json
    depends_on:
      - api
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: {}

networks:
  monitoring: