global:
  scrape_interval: 15s  # Частота опроса метрик

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['weather_api:8000']
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
